Repository chrisegener22/LT-soen341projectF2023, pull requests merged in 2023-11, with the labels that each got.

#52 Make buy offer button
  my-app/src/App.js
  my-app/src/components/OfferForm.js
  my-app/src/components/PropertyDetails.js
Labels: front end

#58 Task 54 login management
  my-app/backend/models/userModel.js
  my-app/backend/package-lock.json
  my-app/backend/package.json
  my-app/backend/routes/usersRoute.js
  my-app/package-lock.json
  my-app/package.json
  my-app/src/components/Login.js
  my-app/src/components/Navbar.js
  my-app/src/components/PropertyCard.js
  my-app/src/components/PropertyDetails.js
  my-app/src/components/Register.js
  my-app/src/index.js
  my-app/src/utils/AuthContext.js
Labels: task

#60 Task 59 create manage brokers page
  my-app/backend/routes/usersRoute.js
  my-app/src/App.js
  my-app/src/components/BrokerCard.js
  my-app/src/components/Brokers.js
  my-app/src/components/Login.js
  my-app/src/components/Navbar.js
  my-app/src/components/PropertyCard.js
Labels: task

#65 Task 61 implement crud operations for broker page
  my-app/backend/models/userModel.js
  my-app/backend/routes/usersRoute.js
  my-app/src/App.js
  my-app/src/components/BrokerAdd.js
  my-app/src/components/BrokerDelete.js
  my-app/src/components/BrokerUpdate.js
  my-app/src/components/Brokers.js
  my-app/src/components/Home.js
  my-app/src/components/Login.js
  my-app/src/components/Navbar.js
  my-app/src/components/PropertyCard.js
  my-app/src/components/PropertyDetails.js
  my-app/src/utils/AuthContext.js
Labels: task

#80 Bug 79 login error when redirected
  my-app/backend/package-lock.json
  my-app/backend/package.json
  my-app/backend/routes/usersRoute.js
  my-app/src/App.js
  my-app/src/components/BrokerCard.js
  my-app/src/components/Brokers.js
  my-app/src/components/Home.js
  my-app/src/components/Login.js
  my-app/src/components/Navbar.js
  my-app/src/components/OfferForm.js
  my-app/src/components/PropertyCard.js
  my-app/src/components/PropertyDetails.js
  my-app/src/context/AuthProvider.js
  my-app/src/index.js
  my-app/src/utils/AuthContext.js
Labels: bug
